/**
 * site-config.schema.ts
 *
 * TypeScript types and Zod validation schema for the site-config.yaml format.
 * This file defines what a valid site configuration looks like.
 *
 * The site-config.yaml is the single source of all site-specific configuration:
 * content types, schemas, prompts, routing rules, cleanup patterns, and LLM settings.
 * It is generated by the `analyse` command and can be edited by humans.
 */

import { z } from "zod";

// ---------------------------------------------------------------------------
// Field definition — describes a single field in a content type schema
// ---------------------------------------------------------------------------

/**
 * Supported field types in the YAML config.
 * These map to Zod types at runtime:
 * - string → z.string()
 * - number → z.number()
 * - boolean → z.boolean()
 * - string[] → z.array(z.string())
 * - image → z.object({ src: z.string(), alt: z.string() }).optional()
 * - object → z.object({ ... }) with nested fields
 */
export const FieldTypeSchema = z.enum([
  "string",
  "number",
  "boolean",
  "string[]",
  "image",
  "object",
]);

export type FieldType = z.infer<typeof FieldTypeSchema>;

export const FieldDefinitionSchema: z.ZodType<FieldDefinition> = z.lazy(() =>
  z.object({
    type: FieldTypeSchema,
    description: z.string().optional(),
    required: z.boolean().optional().default(false),
    items: z
      .lazy(() => z.record(z.string(), FieldDefinitionSchema))
      .optional(),
  })
);

export interface FieldDefinition {
  type: FieldType;
  description?: string;
  required?: boolean;
  /** For object type: nested field definitions */
  items?: Record<string, FieldDefinition>;
}

// ---------------------------------------------------------------------------
// Content type definition — describes one content type (archetype)
// ---------------------------------------------------------------------------

export const ContentTypeDefinitionSchema = z.object({
  /** Content type name (e.g. "blog_post", "team_member") */
  name: z.string().min(1),

  /** URL path patterns that match this content type (regex strings) */
  url_patterns: z.array(z.string()).min(1),

  /** Output directory under content/ */
  output_dir: z.string().min(1),

  /** Schema definition */
  schema: z.object({
    /** Whether to include base fields (title, slug, date, author, etc.) */
    base: z.boolean().default(true),

    /** Extra fields specific to this content type */
    extras: z.record(z.string(), FieldDefinitionSchema).optional().default({}),
  }),

  /** System prompt for the extraction LLM (per content type) */
  extraction_prompt: z.string().min(1),

  /** Required fields that must be non-empty after extraction */
  required_fields: z.array(z.string()).optional().default([]),
});

export type ContentTypeDefinition = z.infer<typeof ContentTypeDefinitionSchema>;

// ---------------------------------------------------------------------------
// Cleanup rule — a named regex pattern for removing boilerplate
// ---------------------------------------------------------------------------

export const CleanupRuleSchema = z.object({
  name: z.string().min(1),
  regex: z.string().min(1),
  flags: z.string().optional().default("gm"),
});

export type CleanupRule = z.infer<typeof CleanupRuleSchema>;

// ---------------------------------------------------------------------------
// Top-level site config
// ---------------------------------------------------------------------------

export const SiteConfigSchema = z.object({
  /** Config format version */
  version: z.number().int().positive(),

  /** Site metadata */
  site: z.object({
    url: z.string().url(),
    name: z.string().min(1),
  }),

  /** Crawl settings */
  crawl: z
    .object({
      skip_patterns: z.array(z.string()).optional().default([]),
    })
    .optional()
    .default({}),

  /** Content type definitions */
  content_types: z.array(ContentTypeDefinitionSchema).min(1),

  /** Boilerplate cleanup rules */
  cleanup: z
    .object({
      patterns: z.array(CleanupRuleSchema).optional().default([]),
    })
    .optional()
    .default({}),

  /** LLM settings */
  llm: z
    .object({
      /** Cloud LLM model for the analyse phase */
      analysis_model: z.string().optional().default("claude-sonnet-4-20250514"),

      /** Local LLM model for the extract phase */
      extraction_model: z.string().optional().default("gemma3:4b"),

      /** Ollama context window size */
      extraction_context_size: z.number().optional().default(8192),

      /** Max chars to send to LLM for metadata extraction */
      extraction_max_chars: z.number().optional().default(4000),
    })
    .optional()
    .default({}),
});

export type SiteConfig = z.infer<typeof SiteConfigSchema>;
